[workspace]
authors = ["Zain-Mrza <you@example.com>"]
channels = ["conda-forge"]
name = "gan_synthesis"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.3.2,<3"
scikit-learn = ">=1.7.1,<2"
matplotlib = ">=3.10.3,<4"
ipykernel = ">=6.29.5,<7"
pip = ">=25.1.1,<26"
nibabel = ">=5.3.2,<6"
tqdm = ">=4.67.1,<5"


[pypi-dependencies]
gan_synthesis = { path = ".", editable = true }
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu128" }
importlib = ">=1.0.4, <2"
